apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: development
  name: johnAutorization
rules:
- apiGroups: [""]
  resource: ["pods"]
  verbs: ["get", "watch", "list", "update", "delete", "create" ]