apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: development
  name: johnAutorizationBinding
subjects:
- kind: User
  name: john
  apiGroups: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: johnAutorization
  apiGroups: rbac.authorization.k8s.io