apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: johnAutorization
rules:
- apiGroups:
    - ""
  resources: ["pods"]
  verbs: ["get", "watch", "list", "update", "delete", "create" ]