apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: johnAutorization
  namespace: development
subjects:
- kind: User
  name: john
  apiGroups: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: johnAutorization
  apiGroups: rbac.authorization.k8s.io
